### ISSUE TITLE
Team Task: Client Meeting Questions

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#1]
Initial discussion and questions planning for client meeting
To be completed on 6/1/2023

**Comment by jiaxinlarhh** [comment]
1. What kind of format and data is required for quarterly reports to be sent by the service centres? 
2. What are some of the sample reports and each of the project records? 
3. What kind of data do you require for data analysis?

**Comment by gohguanlin** [comment]
4. What factors would a regional manager use to decide on sending a request?
5. How many centers does a regional manager take charge of?
6. Does the system require financial data (expenses, donations, etc) to be made available to the regional managers?

**Comment by jingyi823** [comment]
7. Can we decrease the number of volunteers / donors/ employees?
8. Will each project be independently managed solely by each service centre?
9. Are there any security and data privacy concerns to be addressed?

**Comment by yi-kiat** [comment]
10. Are there any platform preferences?
11. Will the system expect high traffic?
12. Is the act of adding a donor by the donor or the regional manager’s discretion?

**Comment by AiXin18** [comment]
13. Does the donor’s donation move together with the donor’s name upon being added to a project?
14. Do you have a preferred color theme, or any app name preferred?
15. Are the regional managers the only users for the system?

**Comment by AiXin18** [comment]
completed on time - 6/1/2023
