### ISSUE TITLE
[D1 Retro]: Team Dynamics & Management

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#103]
Team Dynamics of D1

Areas done well
- Active discussion during class.

Areas of improvement:
- Weekly meeting out of class to discuss progress, task, changes, etc
- Define clear roles and responsibilities for each members

**Comment by AiXin18** [comment]
Team Dynamics of D1

Areas done well
- check on one another progression 

Areas of improvement:
- make all the team members involve in every discussion

**Comment by yi-kiat** [comment]
Team Dynamics of D1

Areas done well
- fast response to each other's queries

Areas of improvement:
- more discussion among one another

**Comment by jiaxinlarhh** [comment]
Team Dynamics of D1

Areas done well
- everyone try their best to be active


Areas of improvement:
- no more last minute work
- trust one another more

**Comment by jingyi823** [comment]
Team Dynamics of D1

Areas done well
- good cooperation among team members 

Areas of improvement:
- every team member update project board consistently

**Comment by jiaxinlarhh** [comment]
Completed on 4/3/2023
