### ISSUE TITLE
[D1 Retro]: Task Allocation & Management

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#105]
Task Allocation and Management for D1:

Areas of improvement:
- No clear task allocation and roles defined for D1 
- WBS was made but was not really adhered to.

**Comment by jiaxinlarhh** [comment]
Areas of improvement:
- No clear roles and responsibilities defined for each team members

**Comment by AiXin18** [comment]
Areas of Improvement:
-  Ability to adapt to changes

**Comment by jingyi823** [comment]
Areas of Improvement:
- monitoring and tracking of assigned tasks progress

**Comment by yi-kiat** [comment]
Areas of improvement:

- assign and perform tasks earlier
