### ISSUE TITLE
[D1 Retro]: Commitments for Ownership

### ISSUE THREAD

**Issue by yi-kiat** [yi-kiat/ICT2106_P3-5#106]
After reviewing our team allocation and management, our team has decided to take up the responsibility of our assigned features.

Commitments for D2:

I will regularly check the project board and cross check the progress of the tasks and the status of the entries in the project board.

**Comment by jiaxinlarhh** [comment]
Commitments for D2:

I will be updating the project board and taking up the responsibilities to the assigned task in the project board.

**Comment by gohguanlin** [comment]
Areas of Improvement:
- There was no clear and concise ownership of classes/features thus everyone was involved in everything and some details like the classes in the class diagram were not checked thoroughly.

Commitments for D2:
As a result I will be taking ownership of the Quarterly Report feature and all it's related classes and diagrams.

**Comment by AiXin18** [comment]
Commitments for D2:

After the D1 consultation, i will be focusing more on the project board to update my own features, as well as taking the responsibility of View Resource and View Form feature.

**Comment by jingyi823** [comment]
Commitments for D2:

After the D1 retrospective with my team members, I will be taking up the responsibility of updating the project board to update the progress of my feature, and creating the resource request form feature.
