### ISSUE TITLE
[D2 Retro] Team Dynamic & Management

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#108]
Team Dynamics of D2

Areas done well
- 
- 
- 

Areas to improve
- 
- 
-

**Comment by AiXin18** [comment]
Team Dynamics of D2

Areas done well
- having a physical meeting every week 
- can update progress more on tele / when we meet up

Areas to improve
- can meet more than once sometimes if needed, and have more discussions

**Comment by jiaxinlarhh** [comment]
Team Dynamics of D2

Areas done well
- Having 2 meetings per week (once in class, once every Friday)
- Consistently updating each other on our progress
- Good communication between active members
- Involvement of all active members and non-active member during all meetings

Areas that can be improved
- Inactive members can be more active
- Inactive members are included in all meetings but are not doing team task

**Comment by yi-kiat** [comment]
Team Dynamics of D2

Areas done well

- Having a regular weekly meeting
- Active facilitation of communication by each member's accord

Areas that can be improved

- Can help recognize ailing members behind in their contributions

**Comment by gohguanlin** [comment]
Team Dynamics of D2

Areas done well
- Progressive work done for report and coding, no last minute work.
- Most members are actively communicating on their work progress


Areas to improve
- Might help if more effort is put into helping team members that might be lacking behind

**Comment by jingyi823** [comment]
Team Dynamics of D2

Areas done well

- Having weekly meeting to do project
- Start work early
- Update project board consistently

Areas to improve

- Team member A should respect team member B.
- Team member A said "Cause I know you will screw up our justification" to team member B, which is mean and harsh. It is not right to hurt other people's feelings.
- Team member A criticize team member B's work and said "You got see how jialat is your ATAM?" to team member B when team member B has already put in effort and time to do the work.

**Comment by AiXin18** [comment]
Reviewed and Closed on: 31/3/2023
