### ISSUE TITLE
[D2 Retro]: Task Allocation & Management

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#109]
Task Allocation and Management for D2:

Areas of improvement:
-
-

**Comment by AiXin18** [comment]
Areas of improvement:

- can try to do task on some 
- update the github board more consistently

Areas of improvement:
- Sometimes we spend a lot of time thinking if a diagram make sense. maybe next time we can think through at home first so when we meet, we can just share out ideas.

**Comment by jiaxinlarhh** [comment]
Areas done well:
- Tasks are allocated clearly every week
- Everyone has a task to aim to complete on every friday
- Task instructions are clear when assigned to everyone

Areas of improvement:
- Can add more tasks weekly to fasten the pace

**Comment by yi-kiat** [comment]
Areas done well:

- Everyone constantly has or can find an idea of what they can do to contribute during D2

Areas of improvement:

- could improve response time of members acknowledging dynamic task allocation

**Comment by gohguanlin** [comment]
Areas done well:

- Most members are well aware of their responsibilities and completes their task

Areas of improvement:

- Could have the members to check-in on each other's progress more often and offer help if required.

**Comment by AiXin18** [comment]
Reviewed and Closed on: 31/3/2023

**Comment by jingyi823** [comment]
Areas done well:

- Every team member puts in effort and time on their tasks.

Areas of improvement:

-  Monitor progress and provide help and support to ensure that team members can complete tasks effectively.
