### ISSUE TITLE
3.1 Software Architecture Design

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#11]
![Image](https://user-images.githubusercontent.com/91781056/218178953-75dca5f9-1825-404a-94ab-e0e1826cc506.png)

Our group is in charge of managing the request and evaluation form and quarterly reports for the regional manager. The request form and performance evaluation component has an interface with their corresponding repository. There are also interfaces provided for other teams to use. We provide module 2 interfaces, including IRequest and IPerformanceEvaluation, for display as they are intended for projects and service centres, respectively. We are using the interface, IReport, offered by module 2 so that the regional manager can deliver performance assessments based on the statistics for each service centre. Additionally, we will give module 3 team 2 all the interfaces for their respective dashboards display for the regional manager.

**Comment by AiXin18** [comment]
Reviewed and Completed on Time: 1/2/2023
