### ISSUE TITLE
[D2 Retro]: Commitments for Ownership

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#110]
Commitments for D2:

**Comment by AiXin18** [comment]
Commitments for D2:

I updated the project board tasks that was assigned to me, and taking up the responsibilities for OCP, factory and feature 1 and 4 of the project.

**Comment by jiaxinlarhh** [comment]
Commitments for D2:

I completed most of the task that was assigned to me and had been consistently updating the project board once I completed my task. I am responsible of my own classes and

**Comment by yi-kiat** [comment]
Commitments for D2:

I am responsible for feature 5, the filter design pattern and the single responsibility applied with it. I have updated my assigned tasks on the project board whenever I accomplished it.

**Comment by gohguanlin** [comment]
Commitments for D2:
Took responsibility for feature 3, Quarterly Report feature and refactoring the respective classes for Single Responsibility Principle and application of Strategy Pattern for the classes. I updated my tasks promptly on github board when I have completed them.

**Comment by jingyi823** [comment]
Commitments for D2:

I took up the responsibilities for making essential changes in the request form (Feature 1) such as adding the dropdownlist for regional manager to select the project name, adding the confirmation popup box "Are you sure you want to submit?" for submit button to prevent regional manager from accidentally submit the request form, contributed in the Factory design pattern as well as I update the project board tasks when I have completed them.

**Comment by AiXin18** [comment]
Reviewed and closed on: 31/3/2023
