### ISSUE TITLE
[D2] 5.2 Design Pattern 2

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#111]
To be completed on:

**Comment by yi-kiat** [comment]
Using the filter pattern for the filter system

For each of the form, the filter needs to filter based on the chosen attributes. Classes made for the attributes according to the pattern, and they implement an interface for the method that filters and chains the results.

It is good for compiling complex queries and the pattern aids in decoupling for easy future reuse.

![Image](https://user-images.githubusercontent.com/94179908/226181442-8fba6947-b016-4ed2-b955-d63a93cd5361.png)

**Comment by yi-kiat** [comment]
Reviewed and acknowledged by team members:
- [x] Guan Lin
- [x] Jing Yi
- [x] Jia Xin
- [x] Ai Xin
