### ISSUE TITLE
[D2] Team Task: Week 11 Demo Meeting Minutes

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#112]
Demo Meeting with Profs:

Feedback mentioned in presentation
- Color consistency
- UI consistency in overall look (eg. search bar)
- Possibility of compound queries for search/filter
- Column alignment
- Hopefully all 5 features by week 13
- Emphasis on data analytics, client wants charts
- Final presentation, no slides required, pure demo
eg. we are presenting module 1

**Comment by gohguanlin** [comment]
Acknowledge by members:

- [x] Jia Xin
- [x] Ai Xin
- [x] Jing Yi
- [x] Yi Kiat
- [x] Guan Lin

**Comment by jiaxinlarhh** [comment]
reviewed on 16/3
