### ISSUE TITLE
5.1 Gantt Chart

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#14]
Our team uses the Gantt Chart as a tool to distribute resources, plan and work around deadlines, and keep track of the completion dates for each assignment assigned to team members.

![Image](https://user-images.githubusercontent.com/91781056/218184508-c2acd288-2812-4d38-a405-40f80ab33371.png)

![Image](https://user-images.githubusercontent.com/91781056/218184570-07a143db-20f3-46e3-8d2a-4b61d5c3eaf1.png)

**Comment by AiXin18** [comment]
Reviewed and Completed on Time: 8/1/2023
