### ISSUE TITLE
Team Task: User Features Ideation

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#2]
The draft idea for the main and backup user features.
To be completed on 6/1/2023

edit: TBC with Team 2 for any clashes by Mon 09/01/23

**Comment by jiaxinlarhh** [comment]
1. Send requests form (to request to add / increase)
2. Login Account (for each of the different center)

**Comment by gohguanlin** [comment]
3.  Automated report generation/submission system for quarterly report (data analysis)

4.  Filter system for display of data(sort from a-z / z-a etc)

**Comment by jingyi823** [comment]
5. Scheduler for board/group meetings? (Event calender kind of thing)
6. Search bar (to quickly navigate to a report)

**Comment by yi-kiat** [comment]
7. Show/hide sender manager name (for request)
8. Gantt chart

**Comment by AiXin18** [comment]
9. Overall dashboard to display data like running cost, donations, etc. for each the centres they manage.
10. Graph representation of data (data analysis of current project)

**Comment by AiXin18** [comment]
completed on time - 6/1/2023
