### ISSUE TITLE
2.3 User Features

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#25]
The following section shows the user features that module 3 has, which are implemented by Team 5. In each of the user feature tables, you will be able to see the interaction happening in the module.

**Comment by gohguanlin** [comment]
Final 5 features 

1.Request additional resources to service managers for a project by providing a form that has to be filled and submitted.
2.Send performance evaluation on service centre with reference to data analysis report.
3.Generation of latest quarterly reports with data analysis of service centre.
4.View past history list of resource requests sent and their statuses.
5.View past history list of project reports.

**Comment by AiXin18** [comment]
Reviewed and Completed on Time: 27/1/2023
