### ISSUE TITLE
2 Requirements and Features

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#4]
Tentative system features are put out by both teams 2 and 5.
Features by each team are already finalized on 17/1/23.

Functional and non-functional requirements are to be stated and put in the report.
To be completed on -

**Comment by gohguanlin** [comment]
Final 5 features 

1.Request additional resources to service managers for a project by providing a form that has to be filled and submitted.
2.Send performance evaluation on service centre with reference to data analysis report.
3.Generation of latest quarterly reports with data analysis of service centre.
4.View past history list of resource requests sent and their statuses.
5.View past history list of project reports.

**Comment by AiXin18** [comment]
The following section will show the functional and non-functional requirements for Module 3, the main features for Module 3, as well as the Use Case Diagram and Description (in appendix) for each of the activities in the Use Case.

**Comment by AiXin18** [comment]
Reviewed and Completed on Time: 18/1/2023
