### ISSUE TITLE
3.2 Component Diagram (Updated)

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#48]
Class Component Diagram

![Image](https://user-images.githubusercontent.com/91781056/218179879-7d6a1e3c-8aef-404f-a446-b4655a341f33.png)

**Comment by AiXin18** [comment]
Team Component Diagram

![Image](https://user-images.githubusercontent.com/91781056/218179998-5ba08f88-915d-4eea-ac6b-4de86a164c44.png)

**Comment by AiXin18** [comment]
Reviewed and Completed on Time: 28/1/2023

**Comment by jiaxinlarhh** [comment]
Final Component Diagram

![2106 -P5 Diagrams - Component Diagram (1)](https://user-images.githubusercontent.com/92164522/218181727-679faf78-5a7b-4940-9778-a1d4ba1fd879.png)

**Comment by jiaxinlarhh** [comment]
Reviewed and Completed on Time: 28/1/2023
