### ISSUE TITLE
6.1 Feature Implementation Plan

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#51]
Some of the thins to be planned before start coding.
To be completed on 2/1/203

**Comment by jiaxinlarhh** [comment]
Controller
1. RequestController
2. Feedback Controller 

Control 
1. RequestControl
2. FeedbackControl

View - React
1. Request.js
2. Feedback.js

Model
1. Request.cs
2. Feedback.cs

Update the dbContext.cs

**Comment by jiaxinlarhh** [comment]
Reviewed and Completed on time - 2/1/2023
