### ISSUE TITLE
[D1 Improvements] Team Meeting for Improvement

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#53]
Things to take note for D1 Retrospection based in prof general comments

To be completed before D2 Submission

**Comment by jiaxinlarhh** [comment]
(Individual Component)
- Daily Update Project Board - EVERYONE take ownership of their own task.
- Reflection - INDIVIDUAL contribution and retrospection 

(Use Case)
- (If have) Include: must have more than one reusable use class
- (If have) Extend: must have extension point
- Use Case should not include things like button, label / UI (NOT USER GUIDE!) - should not be based on wireframe / flow

(Component Diagram)
- Interface
- D2 must provide a list of class for the components

(Class)
- Missing interface class (match component)
- No skeleton code
- Entity no public methods
- (-)attribute, (-)getter (-)setter, (+)functions
- Relationship (classes)
- For D2, class diagram should reflect on how design pattern are applied + support with examples of class design / codes

(Sequence)
- Based on UCDesc + Classes + AD
- To DB: use SQL statement
- Return a list / array (result)

(Architecture Design)
- Wrong - user -> view -> input controller 
- Correct - user -> web server -> input controller
- Correct return - User <- View(output) <- Input controller

[D2 To-Do]:
- detailed design: justify rationale on choosing MVVM
- class diagrams should reflect how design patterns are applied
- should support with examples of class design or codes
- screenshot before and after diagrams and explain the changes.

**Comment by jiaxinlarhh** [comment]
Acknowledge by:

- [x] Guan Lin
- [x] Yi Kiat
- [x] Ai Xin
- [x] Jing Yi
- [x] Jia Xin

**Comment by yi-kiat** [comment]
Reviewed and completed by 3/3/23
