### ISSUE TITLE
[D1 Improvements]: Team Component Diagram

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#54]
Improvements for team component diagram

To be completed before D2 submission

**Comment by jiaxinlarhh** [comment]
- [x] Add in description
- [x] State which team component we are using + providing
- [x] Interface should be added into class diagram
- [x] Include a list of component we are providing / using 
- [x] Include list of classes in the in each component

**Comment by AiXin18** [comment]
Reviewed and completed on: 27/3/2023
