### ISSUE TITLE
[D1 Improvements]: Team Class Diagram

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#55]
Improvements on class diagram

To be completed before D2 Submission

Draft 1:

![Image](https://user-images.githubusercontent.com/91781056/222702185-bf78882b-7650-45fb-a971-bdf6cf01b5f3.png)

**Comment by AiXin18** [comment]
Draft 1
- [x] Need to have boundary class (interface)
- [x] Need to have Relationship 
- [x] Information hiding not implemented correctly
- [x] Need to have Public method in all entities 
- [x] Request: Missing Attributes from code

**Comment by jiaxinlarhh** [comment]
Performance Evaluation Class Diagram:

![Image](https://user-images.githubusercontent.com/92164522/222702862-bc87d4da-d6e0-4ba4-8289-23f0daa4501f.png)

**Comment by gohguanlin** [comment]
Completed first draft of my classes for Quarterly Report Feature



![Image](https://user-images.githubusercontent.com/36472333/222703880-57754732-5407-4796-a5db-19344db716fb.png)

**Comment by jingyi823** [comment]
Request Class Diagram:


![Image](https://user-images.githubusercontent.com/77524281/222703698-fd4062af-e9ce-44c3-ac20-eb956044ee30.png)

**Comment by yi-kiat** [comment]
Reviewed and completed by 3/3/23
