### ISSUE TITLE
1 Requirement Elicitation

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#6]

**Comment by AiXin18** [comment]
This document will introduce the Regional Managers Management Information System (RMMIS) and how this product will help our client, YouthAction, better manage their project. In this introductory section, you will find more information regarding the project scope, its quality attributes, and a document overview to supplement the table of contents in more detail.

**Comment by AiXin18** [comment]
Reviewed and Completed on Time: 9/1/2023
