### ISSUE TITLE
[D2] 3.2 Final Integrated Component Diagram

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#61]
TODO: edit and improve existing component diagram.
To be completed on: 31/3/2023

**Comment by gohguanlin** [comment]
Integrated Component Diagram completed and finalised for our Team.
Live diagram can be accessed [here](https://lucid.app/lucidchart/6d4c7e8e-b431-4daa-9b8d-c29abd4601ad/edit?page=0_0#)

**Comment by gohguanlin** [comment]
Reviewed by member:

- [x] Jia Xin
- [x] Ai Xin
- [x] Yi Kiat
- [x] Guan Lin

**Comment by AiXin18** [comment]
Reviewed and Closed on: 31/3/2023
