### ISSUE TITLE
[D2] 2.3 [Feature #3} [User Feature] [complete / incomplete] [Guan Lin]

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#63]
Feature 3

- [x] completed
- [ ] incomplete

**Comment by gohguanlin** [comment]
![Image](https://user-images.githubusercontent.com/36472333/228009047-d84da8e7-a451-46f0-9d8a-72c8b75765d7.png)

Quarterly Report feature allows the Regional Manager to generate report for the quarter and year that is selected, and with the data of the particular quarter, the data analysis generates a bar chart and a pie chart for visualization purposes, then the Regional Manager can download the report as PDF or Doc file.
