### ISSUE TITLE
[D5] 2.5 [Feature #5} [User Feature] [complete / incomplete] [Yi Kiat]

### ISSUE THREAD

**Issue by AiXin18** [yi-kiat/ICT2106_P3-5#66]
Feature 5

- [x] completed
- [ ] incomplete

**Comment by yi-kiat** [comment]
![Image](https://user-images.githubusercontent.com/94179908/229040541-f97f3bc7-0bc2-4617-8a55-2561386d19ba.png)



![Image](https://user-images.githubusercontent.com/94179908/229040702-5fc01a55-a324-4596-9d79-5abbcd757759.png)




![Image](https://user-images.githubusercontent.com/94179908/229040865-8ddd9549-5748-494c-a39e-925e0d446d7d.png)
