### ISSUE TITLE
[D2] 4.2 Principle 2

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#68]
TODO: Principle 2 of SOLID principle.

To be completed on

**Comment by AiXin18** [comment]
![Image](https://user-images.githubusercontent.com/91781056/225535761-e2d0f097-8524-4d75-8bec-f2c0bca68bbb.png)

Our team will also be discussing the violation of the Open-Closed Principle (OCP As seen in the Figure X above, the current  Request and Performance Evaluation class diagram contains common attributes and methods. 



![Image](https://user-images.githubusercontent.com/91781056/225535982-34608935-5222-43f2-bb0e-b735f09932b8.png)

In the updated class diagram, Figure Y, as shown above, by implementing the principle, an abstract class called AbstractForm is added. This class will contain all the common attributes and getters and setters from the two classes and serves as a common base for the Request Form and Performance Evaluation Form classes, allowing them to share common attributes and behavior. This abstract class will then be inherited by the Request and Performance Evaluation form class without needing to duplicate code. This makes the code more maintainable and easier to extend in the future. 
Furthermore, by using an abstract class, the design is open to extension for scalability as any new types of forms that need to be processed by the regional manager can inherit from the Abstract Form class and leverage its common attributes and behaviors. This reduces the amount of code duplication and ensures consistency across different types of forms, making the code easier to manage and maintain in the long term.

**Comment by AiXin18** [comment]
Reviewed and acknowledged by team members:
- [x]  Yi Kiat
- [x]  Guan Lin
- [x]  Jia Xin
- [x] Jing Yi

**Comment by jiaxinlarhh** [comment]
Completed and closed on 16/3
