### ISSUE TITLE
[D2] 4.1 Principle 1

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#69]
TODO: Principle 1 of SOLID principle.

To be completed on

**Comment by gohguanlin** [comment]
Identified **Single Responsibility Principle** violated for my QuarterlyReport Class.
Currently QuarterlyReport Controller is responsible for mainly:
1. Pulling project progress data via iProgress interface from M2.
2. Compiling data for project progress.
3. Perform data analysis on compiled data.
4. Generation of report.

Therefore there are 4 reasons to change if modifications is required in the class:
1. Ways to interface or format of data from M2
2. Ways or timeframe to compile progress data (Quarterly to Annual)
3. Metrics/algorithm change on how analysis is performed
4. Different format or output is required to be changed

As a result, the responsibilities should be split into 4 different classes namely:

**DataProvider**
- Interface via iProgress from M2 and pull required project progress data.

![Image](https://user-images.githubusercontent.com/36472333/223957525-cdc12c65-6d1d-49b6-baa0-0553dc296c1d.png)



**DataCompiler**
- Takes data from **DataProvider** and compiles it in required timeframe and format.


![Image](https://user-images.githubusercontent.com/36472333/223957707-4ada6f94-2852-41cd-85a2-a8940d374034.png)



**DataAnalysis**
- Takes data from **DataCompiler** and perform data analysis on data.


![Image](https://user-images.githubusercontent.com/36472333/223957972-2b6a0829-5e54-4bde-a417-5980a8aeec45.png)



**ReportGenerator**
- Takes data from **DataCompiler** and **DataAnalysis** to put together a report and prepare it for export.


![Image](https://user-images.githubusercontent.com/36472333/223958058-4434f893-fb5d-41a8-ba39-97e5a433e258.png)

**Comment by gohguanlin** [comment]
Amended class diagram for QuarterlyReport.
The new classes are split according to their responsibilities.

![Image](https://user-images.githubusercontent.com/36472333/224308859-3b0c548c-88fe-436b-96d0-19a7e57d36e4.png)


Reviewed and acknowledged by team members:
- [x] Yi Kiat
- [x] Jing Yi
- [x] Jia Xin
- [x] Ai Xin

**Comment by jiaxinlarhh** [comment]
Completed and closed on 16/3
