### ISSUE TITLE
[D2] 3.1 Final Integrated Class Diagram

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#70]
TODO: Final updated class diagram from D1
To be completed on:

**Comment by gohguanlin** [comment]
[REDACTED]

**Comment by jiaxinlarhh** [comment]
The [link](https://lucid.app/lucidchart/6d4c7e8e-b431-4daa-9b8d-c29abd4601ad/edit?invitationId=inv_15e5d65d-88c8-4cb5-beff-069eef50f68e&page=7TaIsR2S70pv#) provided below grants access to the class level integrated class diagram: https://lucid.app/lucidchart/6d4c7e8e-b431-4daa-9b8d-c29abd4601ad/edit?invitationId=inv_15e5d65d-88c8-4cb5-beff-069eef50f68e&page=7TaIsR2S70pv#

**Comment by jiaxinlarhh** [comment]
Reviewed (Jia Xin) on 30/3/2023

**Comment by AiXin18** [comment]
Reviewed (Ai Xin) on 31/3/2023

**Comment by yi-kiat** [comment]
Reviewed (Yi Kiat) on 31/3/2023

**Comment by gohguanlin** [comment]
Reviewed (Guan Lin) on 31/03/23
