### ISSUE TITLE
[D2] 3.3 Indicate Interfaces used

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#71]
TODO: Indicate interfaces used from other groups in the component diagram
To be completed on:

**Comment by jiaxinlarhh** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-9720d387-7fff-9ccd-8bf6-1d1ae8826764"><div dir="ltr" style="margin-left:0pt;" align="left">

Interface | Providing To
-- | --
IRequest | Module 2 Team 3
IPerformanceEvaluation | Module 2 Team 3
IQuarterlyReport | Module 3 Team 2, Team 5 (Own)
ISearchSystem | Module 3 Team 5 (Own)
IFilterSystem | Module 3 Team 5 (Own)
ICriteria | Module 3 Team 5 (Own)
IReportFormat | Module 3 Team 5 (Own)
IAnalysisAlgorithm | Module 3 Team 5 (Own)

</div></b>
</body>
</html>

**Comment by jiaxinlarhh** [comment]
Checked By: 
- [x] Yi Kiat
- [x] Ai Xin
- [x] Guan Lin

**Comment by yi-kiat** [comment]
Reviewed and closed on: 31/3/2023
