### ISSUE TITLE
[D2] 1.1 Update Team Component Diagram

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#73]
Update Team Component Diagram

To be completed on: 31/3/2023

**Comment by gohguanlin** [comment]
![Image](https://user-images.githubusercontent.com/36472333/222358627-05c047ee-30c3-4360-969b-46584c2482c7.png)

Component Diagram appended to include other team's interface.
Pending review.

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/227979516-34a7f437-a2cb-45c9-9aef-024d5525d957.png)

**Comment by jiaxinlarhh** [comment]
Review

- [x] Aixin
- [x] Yikiat
- [x] Guanlin
- [x] JiaXin

**Comment by yi-kiat** [comment]
Completed and Reviewed on - 28/03/2023
