### ISSUE TITLE
[D2] 7. Project Implementation and Final Interface

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#75]
Project Implementation & Final Interface
This section contains our team’s final interface for Regional Manager.

To be completed on: 30/3/2023

**Comment by jiaxinlarhh** [comment]
Code Implementation
- [x] JiaXin
- [x] GuanLin
- [x] Ai Xin
- [x] Yikiat

Final Screenshot
- [x] JiaXin
- [x] GuanLin
- [x] Ai Xin
- [x] Yikiat

**Comment by AiXin18** [comment]
reviewed and closed on: 31/3/2023
