### ISSUE TITLE
[D2] 3. Team Module Design

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#76]
Final integrated Class Diagram and final integrated Component Diagram. Highlight the classes/components that your team is working on (use a different color for example). Indicate interface to other teams.
Highlight any changes from D1, if no changes from D1 just say no changes.

Below the component diagram, list the classes for your component diagram for cross checking with source code.

To be completed on: 31/3/2023

**Comment by gohguanlin** [comment]
- [x] Final Integrated Class Diagram
- [x] Final Integrated Component Diagram
- [x] Indicate the interface used from other teams

**Comment by AiXin18** [comment]
Reviewed and Closed on: 31/3/2023
