### ISSUE TITLE
[D2] 7.1.1 Resource Request Feature

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#78]
Resource Request Form to be completed on 27/3/2023

**Comment by AiXin18** [comment]
![Image](https://user-images.githubusercontent.com/91781056/227980151-4446bc96-71a1-4cee-9c60-508e8a59418f.png)



A Regional Manager has the ability to submit a formal request form to request additional resources required for a project. The request form includes several categories, such as an extension of the project timeline, an increase in the physical space or area required for the project, an augmentation of the project's financial resources, and an increase in the number of donors and volunteers. These categories can be selected by checking the corresponding checkbox. Moreover, the Regional Manager can provide a detailed description to explain the rationale behind the need for additional resources. This formal request process allows the Regional Manager to communicate their resource needs effectively and efficiently to the appropriate channels (Module 2).

**Comment by AiXin18** [comment]
Checked By: 
- [x] Jia Xin
- [x] Guan Lin
- [x] Yi Kiat

**Comment by jiaxinlarhh** [comment]
Reviewed on 29/3/2023

**Comment by jingyi823** [comment]
`made some changes in the Request form`
Added the dropdownlist for regional manager to select the project name in the Request form and the confirmation box "Are you sure you want to submit?" for the submit button. Only when the 'OK' button is clicked, then the request form will be submitted. This is to prevent user from accidentally submitting the request form if submit button is clicked.



![Image](https://user-images.githubusercontent.com/77524281/228606971-32c38df2-588b-41fb-847e-42783beff540.png)
