### ISSUE TITLE
[D2] 1.2 Update Team Class Diagram

### ISSUE THREAD

**Issue by jiaxinlarhh** [yi-kiat/ICT2106_P3-5#79]
Update Team Class Diagram

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/227139957-83b89c36-0a92-427b-9ce7-40a409b688ad.png)

**Comment by AiXin18** [comment]
Reviewed final class diagram

**Comment by gohguanlin** [comment]
Final class diagram reviewed on 23/03/23

**Comment by yi-kiat** [comment]
Reviewed final class diagram on 23/3/23

**Comment by jiaxinlarhh** [comment]
[Reopen]

![Image](https://user-images.githubusercontent.com/92164522/227980799-550e6e01-4c61-469d-8435-55f26f15832b.png)

**Comment by jiaxinlarhh** [comment]
FInal Review

- [x] Aixin
- [x] Yikiat
- [x] Guanlin
- [x] JiaXin

**Comment by yi-kiat** [comment]
Completed and Reviewed on - 28/03/2023
