### ISSUE TITLE
[D2] 7.1.2 Performance Evaluation Feature

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#80]
Perfomance Evaluation Form to be completed before 30/3/2023

**Comment by AiXin18** [comment]
-

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/228883206-1038635f-17b4-482c-b5b9-7e1dcec12f6d.png)

**Comment by jiaxinlarhh** [comment]
Checked By: 
- [x] Ai Xin
- [x] Guan Lin
- [x] Yi Kiat
