### ISSUE TITLE
[D2] 7.1.3 Quarterly Report Feature

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#81]
Quarterly Report to be completed on 28/3/2023

**Comment by AiXin18** [comment]
Checked By: 
- [x] Jia Xin
- [x] Ai Xin
- [x] Yi Kiat

**Comment by gohguanlin** [comment]
![Image](https://user-images.githubusercontent.com/36472333/228007680-9093c896-1641-4e21-a611-42aa38fb38d7.png)

Quarterly Report feature allows the Regional Manager to generate report for the quarter and year that is selected, and with the data of the particular quarter, the data analysis generates a bar chart and a pie chart for visualization purposes, then the Regional Manager can download the report as PDF or Doc file.

**Comment by jiaxinlarhh** [comment]
Reviewed and close on 31/3/2023
