### ISSUE TITLE
[D2] 7.1.4 View History & Status Feature

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#83]
View History & Status to be completed on 27/3/2023

**Comment by AiXin18** [comment]
![Image](https://user-images.githubusercontent.com/91781056/227981332-4c28ef9f-bd88-496a-af54-d226cdd9c96a.png)


![Image](https://user-images.githubusercontent.com/91781056/227981411-dda18e6d-9bf7-440a-9403-d7c57c450306.png)


As the regional manager, they have the privilege of assessing and reviewing all previous resource requests and personal evaluation forms. By simply clicking on a table record, they can easily access a detailed view of the specific form, which contains all the pertinent information. Furthermore, there are also two useful tools available to aid in navigating through the forms: a search bar and a filter menu. These features will be elaborated upon in the subsequent section.

**Comment by AiXin18** [comment]
Checked By: 
- [x] Jia Xin
- [x] Guan Lin
- [x] Yi Kiat

**Comment by jiaxinlarhh** [comment]
Reviewed on 29/03/2023
