### ISSUE TITLE
[D2] 5. Design Pattern

### ISSUE THREAD

**Issue by yi-kiat** [yi-kiat/ICT2106_P3-5#84]
This section is to describe the implementation of 2 design patterns. Provide evidence (class diagram) and  rationale of using the design pattern.

To be completed on

**Comment by yi-kiat** [comment]
- [x] Design Pattern 1
- [x] Design Pattern 2
- [x] Design Pattern 3

**Comment by AiXin18** [comment]
Reviewed and completed on: 23/3/2023
