### ISSUE TITLE
[D2] 7.1.5 Search & Filter System Feature

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#85]
Search & Filter System to be done before 30/3/2023

**Comment by AiXin18** [comment]
Checked By: 
- [x] Jia Xin
- [x] Ai Xin
- [x] Guan Lin

**Comment by yi-kiat** [comment]
![Image](https://user-images.githubusercontent.com/94179908/229040541-f97f3bc7-0bc2-4617-8a55-2561386d19ba.png)



![Image](https://user-images.githubusercontent.com/94179908/229040702-5fc01a55-a324-4596-9d79-5abbcd757759.png)




![Image](https://user-images.githubusercontent.com/94179908/229040865-8ddd9549-5748-494c-a39e-925e0d446d7d.png)

**Comment by yi-kiat** [comment]
Search and Filter feature allows the Regional Manager to quickly find their desired result. Search works by inputting a keyword that they would type, while the Filter comes with specified attributes and drop down lists with available options to choose from. After selecting the options, the system will sort out the irrelevant request or performance evaluation for the Regional Manager.
