### ISSUE TITLE
[D2] 8.1 Update Gantt Chart

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#93]
Update Gantt Chart to be completed on 30/3/2023

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/228646094-d7f0c82a-62fd-453e-8fae-f8fff18961ee.png)

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/228646190-18f5fdce-702f-4509-a74f-6209fd7e13d4.png)

**Comment by jiaxinlarhh** [comment]
Ganttdown Chart done and updated
