### ISSUE TITLE
[D2] 5.1 Design Pattern 1

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#94]
To be completed on:

**Comment by gohguanlin** [comment]
Strategy Pattern identified for QuarterlyReport.

Extract iAnalysisMethod interface from DataAnalysis
Have separate classes that inherits iAnalysisMethod and override the method with their own algorithm for data analysis.

Extract iReportFormat interface from ReportGenerator
Have separate classes that inherits iReportFormat and override the method individually with their own implementation of how the report should be exported.

The additional classes and interface is highlighted in green.

Amended class diagram:


![Image](https://user-images.githubusercontent.com/36472333/224299230-db9262c3-923c-405b-9669-9f12bcdcd844.png)

**Comment by gohguanlin** [comment]
Reviewed and acknowledged by team members:
- [x] Yi Kiat
- [x] Jing Yi
- [x] Jia Xin
- [x] Ai Xin

**Comment by jiaxinlarhh** [comment]
Completed and closed on 16/3
