### ISSUE TITLE
[D2] 4. Detailed Design

### ISSUE THREAD

**Issue by yi-kiat** [yi-kiat/ICT2106_P3-5#95]
Describe your adoption and appropriate use of SOLID principles in your software design. You need to describe the adoption of at least 2 principles. Talk about how your design evolved/changed as you adopted the SOLID principle and the evidence and rationale of using the adopted principle. Show a before and after class diagram that shows how the class diagram has evolved with the adoption of each of the principle.

To be completed on

**Comment by yi-kiat** [comment]
- [x] Principle 1
- [x] Principle 2

**Comment by gohguanlin** [comment]
Both design principles, checked and reviewed. Changes are reflected on class diagram.
Closed on 16/03.
