### ISSUE TITLE
[D2] 8.2 Update Burndown Chart

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#96]
Update Burndown Chart to be completed on 31/3/2023 before 2359

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/229055420-e4e51197-e1af-4ca6-8986-8eb8e49e9176.png)

**Comment by jiaxinlarhh** [comment]
Completed on 31/3/2023
