### ISSUE TITLE
[D2] 5.3 Design Pattern 3

### ISSUE THREAD

**Issue by gohguanlin** [yi-kiat/ICT2106_P3-5#97]
To be completed on:

**Comment by jingyi823** [comment]
Another design pattern our team will be using is Factory Pattern. Factory pattern can be used to create instances of different validation classes based on the type of form input data.
                                                  
From this figure below, we implemented the factory pattern as a form validator for our forms. The Request class would have multiple checkboxes while the PerformanceEvaluation class would have multiple text boxes and input fields. As each input element may require different validation rules, such as mandatory fields, minimum and maximum length for description text fields, there will be multiple objects created to address each of the elements. This opens up an opportunity to optimize the creation process by making a factory. The ValidatorFactory will provide the TextValidator, CheckboxValidator, and DropDownListValidator to check for their respective charges.



![Image](https://user-images.githubusercontent.com/77524281/229104291-ce9ac485-ccd5-4678-8363-14e45951b50c.png)

**Comment by AiXin18** [comment]
This helps in centralizing validators creation and encapsulating them from the other parts of the code like the Form class, improving the modularity and readability of our code. Thus, the factory pattern helps to facilitate the instantiation of the various types of implementation based on the form selected. 

Another advantage of using the Factory Method pattern for form validation is that it provides a flexible and extensible way to create validation objects. New types of input fields and validation rules can be added without modifying the client code. It also allows for easy testing and maintenance of the validation code, as each validation class can be tested independently and modified as needed.

**Comment by AiXin18** [comment]
Initial Approved Diagram : 

![Image](https://user-images.githubusercontent.com/92164522/226100570-c0a6d16e-87de-4357-81c6-04a3a226c8e8.png)


Reviewed and acknowledged by team members:
- [x]  Yi Kiat
- [x]  Guan Lin
- [x]  Jia Xin

**Comment by jiaxinlarhh** [comment]
Final Factory Design Pattern 

![Image](https://user-images.githubusercontent.com/92164522/228880576-595a2b7c-99df-4062-be0f-8fdf471fd584.png)

**Comment by jiaxinlarhh** [comment]
Completed with a slight delay due to a misunderstanding
Vetted and all approved during team meeting on 30/3/2023
