### ISSUE TITLE
[D2] 8.3 Update Github

### ISSUE THREAD

**Issue by jingyi823** [yi-kiat/ICT2106_P3-5#98]
Update Github Project Board

To be completed everytime until week 13

**Comment by AiXin18** [comment]
Github Project Board
The link to our GitHub lies [here](https://github.com/yi-kiat/ICT2106_P3-5). This is where the team can keep track of one another to see if we have completed our assigned task on time.

![Image](https://user-images.githubusercontent.com/91781056/229080976-3bfbab2d-646d-49f3-9a47-97b6afab679d.png)

**Comment by AiXin18** [comment]
Review and closed on: 31/3/2023
